const IDEAS_FETCH_REQUEST = 'IDEAS_FETCH_REQUEST';
const IDEAS_FETCH_SUCCESS = 'IDEAS_FETCH_SUCCESS';
const IDEAS_FETCH_FAIL = 'IDEAS_FETCH_FAIL';


const IDEAS_UPLOAD_REQUEST = 'IDEAS_UPLOAD_REQUEST';
const IDEAS_UPLOAD_SUCCESS = 'IDEAS_UPLOAD_SUCCESS';
const IDEAS_UPLOAD_FAIL = 'IDEAS_UPLOAD_FAIL';

const IDEAS_DELETE_REQUEST = 'IDEAS_DELETE_REQUEST';
const IDEAS_DELETE_SUCCESS = 'IDEAS_DELETE_SUCCESS';
const IDEAS_DELETE_FAIL = 'IDEAS_DELETE_FAIL';




export {
    IDEAS_FETCH_REQUEST,
    IDEAS_FETCH_SUCCESS,
    IDEAS_FETCH_FAIL,
    IDEAS_UPLOAD_REQUEST,
    IDEAS_UPLOAD_SUCCESS,
    IDEAS_UPLOAD_FAIL,
    IDEAS_DELETE_REQUEST,
    IDEAS_DELETE_SUCCESS,
    IDEAS_DELETE_FAIL,
}