const IDEAS_FETCH_REQUEST = 'IDEAS_FETCH_REQUEST';
const IDEAS_FETCH_SUCCESS = 'IDEAS_FETCH_SUCCESS';
const IDEAS_FETCH_FAIL = 'IDEAS_FETCH_FAIL';


export {
    IDEAS_FETCH_REQUEST,
    IDEAS_FETCH_SUCCESS,
    IDEAS_FETCH_FAIL,
}